### ISSUE TITLE
Downgrade to TLSv1.0/g

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-senzing-base#54]
**Is your feature request related to a problem? Please describe.**
When working with MySQL community edition, problems exist with TLS.

**Describe the solution you'd like**
In the Dockerfile, add

```
RUN sed -i 's/TLSv1.2/TLSv1.0/g' /etc/ssl/openssl.cnf
```
as described in https://github.com/dotnet/dotnet-docker/issues/1109

**Comment by docktermj** [comment]
Note: docker-senzing-base Issue #17 Also concerns TLS.

**Comment by brianmacy** [comment]
I recommend making the minimum be 1.1, not 1.0.  That should resolve the issue without opening up too much.
