### ISSUE TITLE
Enable DockerHub Vulnerability scanning and clean up issues

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-senzing-base#69]
DockerHub supports vulnerability scannaning using snyk
https://snyk.io/blog/integrated-docker-security-scanning-by-snyk-in-docker-hub/

Enable the scanning and fix any vulnerabilities found.

**Comment by mahchiahui** [comment]
open source scanners to try:
- https://github.com/docker/docker-bench-security
- https://github.com/quay/clair

**Comment by mahchiahui** [comment]
paid scanners to try:
- https://app.snyk.io/login?cta=sign-up&loc=pricing-container-free&page=pricing
