### ISSUE TITLE
ALB redirection

### ISSUE THREAD

**Issue by christianswanepoel** [Senzing/docker-senzing-base#74]
I see there is a redirection to Senzing in ALB - Is this intended?
```
Redirect tohttps://hub.senzing.com:443/aws-cloudformation-ecs-senzing-stack-basic/?#{query}
Status code:HTTP_301
```

**Comment by docktermj** [comment]
Were you using `http://` in your initial request?   If so, then yes.

**Comment by christianswanepoel** [comment]
My question is - should this redirection be on our deploy?
i.e Why would we want to redirect away from our own servers - what am I missing?

<img width="1259" alt="Screenshot 2021-05-20 at 10 25 40" src="https://user-images.githubusercontent.com/7249713/118981229-69f8e500-b97a-11eb-85d8-351412d03fcc.png">

**Comment by docktermj** [comment]
@christianswanepoel Oh, I now see what you are asking.  You can redirect to anything you want if there is no URI match.  In the example, the thinking is that if someone requests an unsupported URI, they need more information on what is supported by the cloudformation stack.  So we point them to the GitHub project  "GitHub Pages".  Feel free to modify the Cloudformation template to point to what is appropriate in your case.

(This discussion is probably better held in https://github.com/Senzing/aws-cloudformation-ecs-senzing-stack-basic)
